name: Build Chrome Extension

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Prepare Extension Files
        run: |
          mkdir -p dist/extension
          cp manifest.json dist/extension/
          cp background.js dist/extension/
          cp content.js dist/extension/
          cp popup.html dist/extension/
          cp popup.js dist/extension/
          cp styles.css dist/extension/
          cp -r icons dist/extension/

      - name: Upload Extension Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deepwiki-chrome-extension
          path: dist/extension
          if-no-files-found: error  # 如果找不到檔案則報錯